# MD aliases
alias gl='git log --oneline --all --graph --decorate '
alias gfa='git fetch --all --prune'
alias gti='git $*'
alias gita='git add .'
alias gitb='git branch -a'
alias gitc='git commit'
alias gitcm='git commit -m '
alias gitd='git diff $*'
alias gitmstr='git checkout master'
alias gitp='git push'
alias gitr='git remote -vv'
alias gits='git status'
