" This must be first, because it changes other options as side effect
set nocompatible
set modelines=0

" set file encoding to UTF-8
set encoding=utf-8
set fileencoding=utf-8

" change the mapleader from \ to ,
let mapleader=","

" change colorscheme if supported
"if &t_Co >= 256 || has("gui_running")
   colorscheme matrix
"endif

"if exists('+colorcolumn')
"    set colorcolumn=80
"else
"    hi OverLength ctermbg=7 ctermfg=white guibg=#FFD9D9
"    match OverLength '\%>80v.\+'
"endif

" change font if supported
if has("gui_running")

  set lines=34 columns=134
  
    if exists('+colorcolumn')
        set colorcolumn=125
    else
        hi OverLength ctermbg=7 ctermfg=white guibg=#FFD9D9
        match OverLength '\%>132v.\+'
    endif

    if has('win32') || has('win64')
        set lines=35 columns=150
        colorscheme evening_mdupuis
        let $MYVIMRC="C:\\Travail\\Apps\\Vim\\vimrc"
    endif

  "
    if has("gui_gtk2")
        set guifont=mononoki\ 12
    elseif has("gui_win32") || has('win64')
        set guifont=mononoki:h11:cANSI
    endif
endif

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>
nmap <leader>l :set list!<CR>
" clearing highlighted searches
nmap <silent> ,. :nohlsearch<CR>

" CTRL-F2 removes/shows Commandbar and menubar
map <silent> <C-F2> :if &guioptions =~# 'T' <Bar>
                         \set guioptions-=T <Bar>
                         \set guioptions-=m <bar>
                    \else <Bar>
                         \set guioptions+=T <Bar>
                         \set guioptions+=m <Bar>
                    \endif<CR> 
" hide command and menu bars by default
set guioptions-=T "<Bar>
set guioptions-=m "<bar>

" Hides buffers instead of closing them
set hidden

set nowrap        " don't wrap lines
set backspace=indent,eol,start
                  " allow backspacing over everything in insert mode
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set number        " always show line numbers
set relativenumber "display how far away each line is from the current one
set shiftwidth=4  " number of spaces to use for autoindenting
set softtabstop=4 " Make sure it's the same as shitfwidth
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set tabstop=4     " a tab is four spaces
set expandtab     " All tab characters are 4 space characters
set showmatch     " set show matching parenthesis
set ignorecase    " ignore case when searching
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep

set nobackup

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

if &t_Co > 2 || has("gui_running")
   " switch syntax highlighting on, when the terminal has colors
   syntax on
endif

" show whitespaces
set nolist
set listchars=tab:▸\ ,eol:¬,trail:.,extends:#,nbsp:.
autocmd filetype html,xml,sql set nolist  "listchars-=tab:>.
"Invisible character colors 
highlight NonText guifg=grey40
highlight SpecialKey guifg=grey40

nnoremap <F5> :buffers<CR>:buffer<Space>

" remap CTRL-hjkl to move between windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

inoremap <C-h> <C-w>h
inoremap <C-j> <C-w>j
inoremap <C-k> <C-w>k
inoremap <C-l> <C-w>l

" disable arrow keys in insert and normal modes
"nnoremap <up> <nop>
"nnoremap <down> <nop>
"nnoremap <left> <nop>
"nnoremap <right> <nop>
"inoremap <up> <nop>
"inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>

set laststatus=2
set statusline=                           " resets the status line
"set statusline+=%<\                       " cut at start
set statusline+=%2*[%n%H%M%R%W]\          " flags and buf no
set statusline+=%-40f\                    " path
set statusline+=%=%5*%{&ff}\              "file format
set statusline+=%=%1*%y\                  " file type
set statusline+=%10((%l,%c)%)\            " line and column
set statusline+=%P                        " percentage of file

