#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
fi

#set the theme.toml config
#echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands-0.pipe
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"


#set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore
elif [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

monitor=HDMI2 offsetx=0 width=3440 polybar -c $SCRIPTPATH/polybar.config mainbar0 &> /dev/null &
monitor=HDMI1 offsetx=0 width=1920 polybar -c $SCRIPTPATH/polybar.config mainbar1 &> /dev/null &

#index=0
#monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
#leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
#do 
  #barname="mainbar$index"
  #monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  #let index=index+1
#done

